version: '3'
services:
    haproxy:
        container_name: lb
        environment:
            - CERT1=mysite.com, www.mysite.com
            # - CERT2=yoursite.com, www.yoursite.com
            - EMAIL=my.mail
            - STAGING=false
        volumes:
            - './letsencrypt:/etc/letsencrypt'
            - './haproxy.cfg:/etc/haproxy/haproxy.cfg'
        networks:
            - lbnet
        ports:
            - '80:80'
            - '443:443'
            - '89:89'
        image: 'ghcr.io/ociera/docker-haproxy-letsencrypt-tb:master'
    nginx:
        container_name: www
        networks:
            - lbnet
        image: nginx

networks:
  lbnet:
